openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: production API server
    url: https://app-hi.com/api/
  - description: development API server
    url: http://localhost:3000/

info:
  version: "1.0.0"
  title: hi-app
  description: HiのAPIサーバー

paths:
  "/users/{userId}":
    get:
      tags:
        - Users
      description: get UserWithRelatedData
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithRelatedData"
        "400":
          description: not found response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - Users
      description: register user
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationDto"
      responses:
        "201":
          description: created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserWithRelatedData"

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
        statusCode:
          type: integer

    User:
      type: object
      properties:
        _id:
          type: string
          nullable: false
        email:
          type: string
          nullable: false
        userName:
          type: string
          nullable: false
        name:
          type: string
          nullable: false
    UserWithRelatedData:
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            followings:
              type: array
              nullable: false
              items:
                $ref: "#/components/schemas/User"
            followers:
              type: array
              nullable: false
              items:
                $ref: "#/components/schemas/User"
            getUpAt:
              type: string
              nullable: false
            daysToAlarm:
              type: array
              nullable: false
              items:
                type: boolean
                example: [true, false, false, true, false, true, true]
    UserRegistrationDto:
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            getUpAt:
              type: string
              nullable: false
            daysToAlarm:
              type: array
              nullable: false
              items:
                type: boolean
                example: [true, false, false, true, false, true, true]
            deviceToken:
              type: string
              nullable: false
