version: "3.7"

services:
  app:
    image: node:22-alpine3.19
    command: sh -c "yarn install && yarn run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  todo-mysql-data:
